apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/stage
    server: 35.196.21.222    
    