apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  storageClassName: standard
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/stage
    server: 10.32.208.2